name: build-apps

on: [push]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.14.0]
        os: [ubuntu-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v7

      - name: Setup Node env
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📁 Install Dependencies and build the app 🛠️
        run: bash setup.sh

